In [2]:
import requests
import pandas as pd

Get all event_tickers for the Serie

In [3]:
EVENTS_API = "https://api.elections.kalshi.com/trade-api/v2/events" 
#SERIES_TICKER = "KXCPIYOY" #possible tickers for inflation: KXCPI, KXCPIYOY, KXLCPIMAXYOY, KXECONSTATCPIYOY, KXCPICOREYOY, KXECONSTATCPICORE (source: https://kalshi.com/category/economics/inflation)

def get_eventtickers_from_series(series_ticker):
    series_params= {
            "series_ticker": series_ticker,
            "status": "settled",
            "limit": 200 #max
        }
    response = requests.get(EVENTS_API, params=series_params)
    events_data = response.json()['events']
    events_df = pd.DataFrame(events_data)
    return events_df['event_ticker']

Get all the markets for an event

In [4]:

HISTORICAL_API = "https://api.elections.kalshi.com/trade-api/v2/historical/markets"
#EVENT_TICKER = "CPIYOY-23MAY" # KXCPIYOY-26FEB	OF KXCPI-26FEB

def get_markets_from_event(event_ticker):
    event_params= {
        "event_ticker": event_ticker,
        "status": "settled",
        "limit": 1000 #max
    }
    response = requests.get(HISTORICAL_API, params=event_params)
    market_data = response.json()['markets']
    market_data_df = pd.DataFrame(market_data)

    columns = [
        "expiration_value",
        "floor_strike",
        "last_price_dollars",
        "liquidity_dollars",
        "no_ask_dollars",
        "no_bid_dollars",
        "notional_value_dollars",
        "open_interest_fp",
        "previous_price_dollars",
        "previous_yes_ask_dollars",
        "previous_yes_bid_dollars",
        "price_ranges",
        "result",
        "settlement_value_dollars",
        "ticker",
        "title",
        "volume_24h_fp",
        "volume_fp",
        "yes_ask_dollars",
        "yes_ask_size_fp",
        "yes_bid_dollars",
        "yes_bid_size_fp",
    ]

    filtered_df = market_data_df.reindex(columns=columns).copy()
    return filtered_df

Run all code

In [5]:
event_tickers = get_eventtickers_from_series("KXCPIYOY") #must be all capitals
market_dfs = []
market_data_by_event = {}
for event_ticker in event_tickers:
    market_data = get_markets_from_event(event_ticker)
    market_data["event_ticker"] = event_ticker
    market_dfs.append(market_data)
    market_data_by_event[event_ticker] = market_data

all_market_data = pd.concat(market_dfs, ignore_index=True)
display(all_market_data)
print(f"Collected {len(all_market_data)} rows from {len(market_dfs)} events")

,event_ticker,can_close_early,close_time,created_time,expected_expiration_time,expiration_time,expiration_value,floor_strike,fractional_trading_enabled,last_price_dollars,...,title,updated_time,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title,fee_waiver_expiration_time
0,KXCPIYOY-25NOV,True,2025-12-18T13:29:00Z,2025-08-20T16:26:30.260344Z,2025-12-10T15:00:00Z,2026-03-11T15:00:00Z,2.7,3.1,False,0.0800,...,Will the rate of CPI inflation be above 3.1% f...,2026-02-19T08:48:16.628714Z,0.00,189538.00,1.0000,0.00,0.0000,0.00,Above 3.1%,NaN
1,KXCPIYOY-25NOV,True,2025-12-18T13:29:00Z,2025-08-20T16:26:30.260344Z,2025-12-10T15:00:00Z,2026-03-11T15:00:00Z,2.7,3.0,False,0.3200,...,Will the rate of CPI inflation be above 3.0% f...,2026-02-19T08:48:16.628714Z,0.00,105245.00,1.0000,0.00,0.0000,0.00,Above 3.0%,NaN
2,KXCPIYOY-25NOV,True,2025-12-18T13:29:00Z,2025-08-20T16:26:30.260344Z,2025-12-10T15:00:00Z,2026-03-11T15:00:00Z,2.7,2.9,False,0.7000,...,Will the rate of CPI inflation be above 2.9% f...,2026-02-19T08:48:16.628714Z,0.00,240527.00,1.0000,0.00,0.0000,0.00,Above 2.9%,NaN
3,KXCPIYOY-25NOV,True,2025-12-18T13:29:00Z,2025-08-20T16:26:30.260344Z,2025-12-10T15:00:00Z,2026-03-11T15:00:00Z,2.7,2.8,False,0.9600,...,Will the rate of CPI inflation be above 2.8% f...,2026-02-19T08:48:16.628714Z,0.00,178361.00,1.0000,0.00,0.0000,0.00,Above 2.8%,NaN
4,KXCPIYOY-25NOV,True,2025-12-18T13:29:00Z,2025-08-20T16:26:30.260344Z,2025-12-10T15:00:00Z,2026-03-11T15:00:00Z,2.7,2.7,False,0.9900,...,Will the rate of CPI inflation be above 2.7% f...,2026-02-19T08:48:16.628714Z,0.00,25397.00,1.0000,0.00,0.0000,0.00,Above 2.7%,NaN

Collected 480 rows from 40 events

In [6]:
display(all_market_data)

,event_ticker,can_close_early,close_time,created_time,expected_expiration_time,expiration_time,expiration_value,floor_strike,fractional_trading_enabled,last_price_dollars,...,title,updated_time,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title,fee_waiver_expiration_time
0,KXCPIYOY-25NOV,True,2025-12-18T13:29:00Z,2025-08-20T16:26:30.260344Z,2025-12-10T15:00:00Z,2026-03-11T15:00:00Z,2.7,3.1,False,0.0800,...,Will the rate of CPI inflation be above 3.1% f...,2026-02-19T08:48:16.628714Z,0.00,189538.00,1.0000,0.00,0.0000,0.00,Above 3.1%,NaN
1,KXCPIYOY-25NOV,True,2025-12-18T13:29:00Z,2025-08-20T16:26:30.260344Z,2025-12-10T15:00:00Z,2026-03-11T15:00:00Z,2.7,3.0,False,0.3200,...,Will the rate of CPI inflation be above 3.0% f...,2026-02-19T08:48:16.628714Z,0.00,105245.00,1.0000,0.00,0.0000,0.00,Above 3.0%,NaN
2,KXCPIYOY-25NOV,True,2025-12-18T13:29:00Z,2025-08-20T16:26:30.260344Z,2025-12-10T15:00:00Z,2026-03-11T15:00:00Z,2.7,2.9,False,0.7000,...,Will the rate of CPI inflation be above 2.9% f...,2026-02-19T08:48:16.628714Z,0.00,240527.00,1.0000,0.00,0.0000,0.00,Above 2.9%,NaN
3,KXCPIYOY-25NOV,True,2025-12-18T13:29:00Z,2025-08-20T16:26:30.260344Z,2025-12-10T15:00:00Z,2026-03-11T15:00:00Z,2.7,2.8,False,0.9600,...,Will the rate of CPI inflation be above 2.8% f...,2026-02-19T08:48:16.628714Z,0.00,178361.00,1.0000,0.00,0.0000,0.00,Above 2.8%,NaN
4,KXCPIYOY-25NOV,True,2025-12-18T13:29:00Z,2025-08-20T16:26:30.260344Z,2025-12-10T15:00:00Z,2026-03-11T15:00:00Z,2.7,2.7,False,0.9900,...,Will the rate of CPI inflation be above 2.7% f...,2026-02-19T08:48:16.628714Z,0.00,25397.00,1.0000,0.00,0.0000,0.00,Above 2.7%,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,CPIYOY-22NOV,True,2022-12-13T13:25:00Z,2022-12-07T14:55:41.498492Z,2022-12-13T15:00:00Z,2022-12-20T15:00:00Z,7.1,NaN,False,0.6500,...,Will the rate of CPI inflation be above 7.2% f...,2022-12-13T15:03:11.945395Z,0.00,975.00,0.7000,0.00,0.6500,0.00,Above 7.2%,NaN
476,CPIYOY-22NOV,True,2022-12-13T13:25:00Z,2022-12-07T14:55:41.498492Z,2022-12-13T15:00:00Z,2022-12-20T15:00:00Z,7.1,NaN,False,0.7400,...,Will the rate of CPI inflation be above 7.1% f...,2022-12-13T15:03:06.96541Z,0.00,2416.00,0.8200,0.00,0.7700,0.00,Above 7.1%,NaN
477,CPIYOY-22NOV,True,2022-12-13T13:25:00Z,2022-12-07T14:55:41.498492Z,2022-12-13T15:00:00Z,2022-12-20T15:00:00Z,7.1,NaN,False,0.9400,...,Will the rate of CPI inflation be above 7.0% f...,2022-12-13T15:03:00.670417Z,0.00,7011.00,0.9700,0.00,0.9400,0.00,Above 7.0%,NaN
478,CPIYOY-22NOV,True,2022-12-13T13:25:00Z,2022-12-07T14:55:41.498492Z,2022-12-13T15:00:00Z,2022-12-20T15:00:00Z,7.1,NaN,False,0.9300,...,Will the rate of CPI inflation be above 6.9% f...,2022-12-13T15:02:55.291061Z,0.00,1282.00,0.9900,0.00,0.9700,0.00,Above 6.9%,NaN
479,CPIYOY-22NOV,True,2022-12-13T13:25:00Z,2022-12-07T14:55:41.498492Z,2022-12-13T15:00:00Z,2022-12-20T15:00:00Z,7.1,NaN,False,0.9900,...,Will the rate of CPI inflation be above 6.8% f...,2022-12-13T15:02:48.240614Z,0.00,1028.00,1.0000,0.00,0.9800,0.00,Above 6.8%,NaN